name: cloudgram
description: CloudGram - Unlimited Cloud Storage via Telegram
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Telegram API
  http: ^1.2.0
  dio: ^5.4.0

  # File Picker & Media
  file_picker: ^8.0.0
  image_picker: ^1.1.2
  photo_manager: ^3.3.0
  permission_handler: ^11.3.0

  # UI & Design
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  lottie: ^3.1.0
  cached_network_image: ^3.3.1
  percent_indicator: ^4.2.3
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  animations: ^2.0.11
  flutter_animate: ^4.5.0

  # Media Player
  video_player: ^2.8.3
  chewie: ^1.8.0
  audioplayers: ^6.0.0
  just_audio: ^0.9.39

  # Storage & State
  shared_preferences: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get: ^4.6.6
  provider: ^6.1.2

  # Utils
  path_provider: ^2.1.3
  path: ^1.9.0
  mime: ^1.0.5
  intl: ^0.19.0
  open_file: ^3.3.2
  share_plus: ^9.0.0
  connectivity_plus: ^6.0.3
  flutter_local_notifications: ^17.2.1+2
  image: ^4.2.0
  crypto: ^3.0.3
  uuid: ^4.4.2
  url_launcher: ^6.3.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
